### ISSUE TITLE
While describing each project in a series, year displayed below the series is wrong

### ISSUE THREAD

**Issue by shivasdst** [arjunkashyap/kscst-mvc#51]
While describing each project in a series, year displayed below the series is not the same as the one while we list all the porjects in a series. In all the cases it is showing 2012-2013.

http://www.kscst.iisc.ernet.in/sppArchive/public/describe/project/030/5216
http://www.kscst.iisc.ernet.in/sppArchive/public/listing/projects/030

**Comment by arjunkashyap** [comment]
Resolve as Commit No. 193.
